<?php
/**
 * @file
 * Code for the NextEuropa Integration Department Consumer feature.
 */

include_once 'dt_integration_department_consumer.features.inc';

/**
 * Implements hook_cron().
 */
function dt_integration_department_consumer_cron() {
  try {
    $consumer = \Drupal\integration_consumer\ConsumerFactory::getInstance('department');
    $consumer->processImport();
  }
  catch (\Drupal\integration\Exceptions\BaseException $e) {
    watchdog_exception("integration", $e);
  }
}

/**
 * Implements hook_integration_consumer_migrate_post_import().
 */
function dt_integration_department_consumer_integration_consumer_migrate_post_import($consumer) {
  $map = $consumer->getMap();
  foreach ($map as $key) {
    $nid = $key->destid1;
    $node = node_load($nid);
    $wrapper = entity_metadata_wrapper('node', $node);
    $wrapper->field_core_introduction->format->set('full_html');
    $wrapper->save();
    workbench_moderation_moderate($node, 'published');
  }
}
