<?php
/**
 * @file
 * Code for the NextEuropa Integration Department Consumer feature.
 */

include_once 'dt_integration_department_consumer.features.inc';

function dt_integration_department_consumer_cron() {
  try {
    $consumer = \Drupal\integration_consumer\ConsumerFactory::getInstance('department');
    $consumer->processImport();
  }
  catch (\Drupal\integration\Exceptions\BaseException $e) {
    watchdog_exception("integration", $e);
  }
}
